modLoader = "javafml"
loaderVersion = "[${forge_version},)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "createutil"
version = "${version}"
displayName = "Create: Control Utilities"
authors = "kawaiicakes"
description = '''
'''
logoFile = "icon.png"

[[dependencies.createutil]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.createutil]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.createutil]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"